Compass:
    Material: COMPASS
    Short: 0
    Name: "&bTeleporter"
    Lore: "&fSo many custom"
    JoinSlot: 4
    DropsDisabled: false
Inventory:
   Slots: 9
   Name: "&0My Custom Inventory"
Items:
 '1':
    Material: WOOL
    Slot: 4
    Amount: 1
    Short: 5
    Name: "&a&lMagic Wool"
    Lore: "&7&oSo much magic..."
    Command: pl